### ISSUE TITLE
Ruby 3.3.5 + focal doesn't seem to be on Docker Hub 

### ISSUE THREAD

**Issue by veganstraightedge** [ruby/docker-images#105]
Like https://github.com/ruby/docker-images/issues/85, but for todays Ruby 3.3.5 release :)

**Comment by hsbt** [comment]
I fixed that at https://github.com/ruby/docker-images/commit/bd0bcf15cd786175c7852806789a7e528dca74c3

https://github.com/ruby/docker-images/pkgs/container/ruby/267905004?tag=3.3.5-focal

**Comment by veganstraightedge** [comment]
thank you!
