### ISSUE TITLE
Ruby on Newer Ubuntu Image

### ISSUE THREAD

**Issue by jd-sandk** [ruby/docker-images#108]
When can we expect the latest ruby with an updated Ubuntu Image?

For Example: Ruby v3.3.5 installed on Ubuntu 24.04 (LTS)

[We're facing issue due to the old OpenSSL Version currently supplied, and need OpenSSL Version: `3.3.2`]

**Comment by hsbt** [comment]
We already have `rubylang/ruby:3.3.5-noble`.
