### ISSUE TITLE
Missing tags on docker.io for noble versions

### ISSUE THREAD

**Issue by ParcellyStefan** [ruby/docker-images#111]
Other than the README suggests, there seem to be only master/nightly versions with `noble` available on docker.io. I just tried to pull `rubylang/ruby:3.1.6-noble` and it failed. It works perfectly fine with `rubylang/ruby:3.1.6-jammy`.
Also, when looking at https://hub.docker.com/r/rubylang/ruby/tags?name=3.1.6, there is no tag listed for `noble` - only `bionic`, `focal` and `jammy` are listed.

Is there a way to get an image for Ruby 3.1.6 based on Ubuntu Noble?

**Comment by hsbt** [comment]
I published that now: https://github.com/ruby/docker-images/actions/runs/11813329335/job/32910163166

**Comment by ParcellyStefan** [comment]
That was fast - thank you!
